name: Build Android on Push

on:
  push:
    branches:
      - main   # Change la branche ici si tu veux d√©clencher sur autre chose (ex: dev)

jobs:
  build:
    uses: ./.github/workflows/build_android.yml
    with:
      build_type: main
      metamask_environment: qa
